<a href="https://colab.research.google.com/github/gabrielhierro/LinguagensDeProgramacao/blob/main/AtividadePraticaNumPy/Atividade_Pratica_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
pip install numpy

In [12]:

import numpy as np

print('Versão do NumPy:', np.__version__)


Versão do NumPy: 2.1.3


### Nível 1: Básico - Faturamento Semanal e Filtros



Sua primeira tarefa envolve analisar o volume de vendas de uma única loja durante uma semana comercial.

**Passo 1:** Crie um array unidimensional chamado pecas_vendidas contendo o histórico diário da semana: [150, 120, 90, 210, 300, 250, 180] utilizando a função np.array().

In [13]:
import numpy as np

# Criação do array unidimensional com o histórico diário
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])

# Exibindo o resultado
print("Peças vendidas:", pecas_vendidas)

Peças vendidas: [150 120  90 210 300 250 180]


**Passo 2:** A gerência pediu uma estimativa rápida de faturamento. Sabendo que o preço médio de cada peça é de R$ 50,00, crie um novo array multiplicando o array original por 50. Observe como o NumPy aplica essa operação matemática a todos os elementos de uma só vez, sem a necessidade de escrever laços de repetição (operações vetorizadas).


In [14]:
# Multiplicando o array original pelo preço médio da peça (R$ 50,00)
faturamento = pecas_vendidas * 50

# Exibindo o resultado
print("Faturamento diário estimado (R$):")
print(faturamento)

Faturamento diário estimado (R$):
[ 7500  6000  4500 10500 15000 12500  9000]


**Passo 3:** Identifique os dias de pico. Crie uma máscara booleana para filtrar e extrair apenas os dias em que a loja vendeu estritamente mais de 200 peças (ex: pecas_vendidas > 200).


In [15]:
# Criando a máscara booleana (retorna True onde a condição for atendida)
mascara_pico = pecas_vendidas > 200

# Extraindo apenas os valores que correspondem a True na máscara
vendas_pico = pecas_vendidas[mascara_pico]

# Exibindo os resultados
print("Máscara booleana gerada:", mascara_pico)
print("Vendas nos dias de pico (> 200):", vendas_pico)

Máscara booleana gerada: [False False False  True  True  True False]
Vendas nos dias de pico (> 200): [210 300 250]


### Nível 2: Intermediário - Múltiplas Filiais e Falhas de Sistema



Agora você precisa compilar os dados de três filiais diferentes ao longo de quatro dias. A matriz resultante deverá representar as lojas nas linhas e os dias nas colunas.

**Passo 1:** Crie uma matriz 2D a partir das seguintes listas para representar as vendas:
Loja A: [200, 220, np.nan, 250] (Houve uma falha no sistema no $3^{\circ}$ dia, gerando um valor não-número).
Loja B: [150, 180, 160, 190]
Loja C: [300, 310, 290, 330]


In [16]:
# Criando as listas para cada loja
loja_a = [200, 220, np.nan, 250]
loja_b = [150, 180, 160, 190]
loja_c = [300, 310, 290, 330]

# Combinando as listas em uma matriz 2D
vendas_filiais = np.array([loja_a, loja_b, loja_c])

# Exibindo a matriz resultante
print("Matriz de vendas das filiais (linhas = lojas, colunas = dias):")
print(vendas_filiais)

Matriz de vendas das filiais (linhas = lojas, colunas = dias):
[[200. 220.  nan 250.]
 [150. 180. 160. 190.]
 [300. 310. 290. 330.]]


**Passo 2:** Calcule o total de peças vendidas por cada loja (agregando pelas linhas). Para isso, aplique a função de soma especificando o parâmetro axis $=1$.


In [17]:
# Calculando a soma ao longo das colunas (axis=1) para obter o total de cada linha (loja)
total_por_loja = np.sum(vendas_filiais, axis=1)

# Exibindo o resultado
print("Total de vendas por loja (A, B e C respectivamente):")
print(total_por_loja)

Total de vendas por loja (A, B e C respectivamente):
[  nan  680. 1230.]


**Passo 3:** A diretoria quer saber a média diária geral da rede. Como os dados reais frequentemente possuem lacunas, calcule a média utilizando a função do NumPy que ignora os valores nan. Se você usar a média normal, o resultado será contaminado e invalidará o relatório.

In [18]:
# Calculando a média de toda a matriz ignorando os valores NaN
media_diaria_geral = np.nanmean(vendas_filiais)

# Exibindo o resultado
print("Média diária geral da rede (ignorando falhas no sistema):")
print(media_diaria_geral)

Média diária geral da rede (ignorando falhas no sistema):
234.54545454545453


**Passo 4:** A meta diária de cada loja é vender 200 peças. Utilize a função np.where() para criar uma nova matriz condicional, onde os valores maiores ou iguais a 200 sejam substituídos pelo texto 'Meta Atingida', e os valores inferiores sejam substituídos por 'Abaixo'.


In [19]:
# Utilizando np.where(condicao, valor_se_verdadeiro, valor_se_falso)
status_metas = np.where(vendas_filiais >= 200, 'Meta Atingida', 'Abaixo')

# Exibindo o resultado
print("Status das metas diárias por loja:")
print(status_metas)

Status das metas diárias por loja:
[['Meta Atingida' 'Meta Atingida' 'Abaixo' 'Meta Atingida']
 ['Abaixo' 'Abaixo' 'Abaixo' 'Abaixo']
 ['Meta Atingida' 'Meta Atingida' 'Meta Atingida' 'Meta Atingida']]


### Nível 3: Avançado - Categorização e Destaques de Marketing



Nesta etapa final, você fará uma análise focada no perfil das vendas e no sucesso das campanhas publicitárias.

**Passo 1:** Para simular uma base de clientes, utilize o gerador moderno com uma semente fixa (np.random.default_rng()) para que os resultados sejam reproduzíveis. Crie uma amostra com 50 vendas sorteadas entre as opções ['Eletrônicos', 'Roupas', 'Casa'].


In [20]:
# Inicializando o gerador moderno com uma semente fixa (ex: 42) para reprodutibilidade
rng = np.random.default_rng(seed=42)

# Definindo as opções de departamentos
opcoes = ['Eletrônicos', 'Roupas', 'Casa']

# Criando a amostra de 50 vendas com o método choice
amostra_vendas = rng.choice(opcoes, size=50)

# Exibindo os resultados gerados
print("Amostra de 50 vendas sorteadas:")
print(amostra_vendas)

Amostra de 50 vendas sorteadas:
['Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas' 'Casa' 'Eletrônicos'
 'Casa' 'Eletrônicos' 'Eletrônicos' 'Roupas' 'Casa' 'Casa' 'Casa' 'Casa'
 'Casa' 'Roupas' 'Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas'
 'Eletrônicos' 'Casa' 'Casa' 'Roupas' 'Roupas' 'Casa' 'Roupas' 'Roupas'
 'Roupas' 'Eletrônicos' 'Eletrônicos' 'Roupas' 'Casa' 'Eletrônicos' 'Casa'
 'Casa' 'Eletrônicos' 'Roupas' 'Eletrônicos' 'Casa' 'Casa' 'Roupas'
 'Eletrônicos' 'Casa' 'Roupas' 'Casa' 'Casa' 'Casa']


**Passo 2:** Determine o volume de vendas de cada departamento. Utilize a função np.unique habilitando o argumento return_counts=True para obter os valores únicos e suas respectivas contagens - esta é uma forma rápida de fazer o equivalente numérico de contagem de categorias.


In [21]:
# Utilizando np.unique para extrair as categorias e contar a ocorrência de cada uma
departamentos_unicos, contagens = np.unique(amostra_vendas, return_counts=True)

# Exibindo os resultados de forma organizada
print("Departamentos únicos encontrados:")
print(departamentos_unicos)
print("\nVolume de vendas por departamento (contagem):")
print(contagens)

Departamentos únicos encontrados:
['Casa' 'Eletrônicos' 'Roupas']

Volume de vendas por departamento (contagem):
[21 12 17]


**Passo 3:** O time de marketing enviou um array com o faturamento de cinco campanhas simultâneas: [12000, 45000, 23000, 89000, 31000]. Identifique rapidamente a campanha campeã utilizando o método que retorna o índice (posição) do maior valor do array.


In [22]:
# Array com o faturamento das campanhas
faturamento_campanhas = np.array([12000, 45000, 23000, 89000, 31000])

# Encontrando o índice do maior valor utilizando argmax
indice_campea = np.argmax(faturamento_campanhas)

# Acessando o valor da campanha vencedora pelo índice
valor_campeao = faturamento_campanhas[indice_campea]

# Exibindo os resultados
print(f"Índice da campanha campeã: {indice_campea}")
print(f"Faturamento da campanha campeã: R$ {valor_campeao}")

Índice da campanha campeã: 3
Faturamento da campanha campeã: R$ 89000




---



### Atividade Prática: Organização e Transformação de Dados com NumPy



Esta nova bateria de exercícios simula tarefas reais de preparação de bases de dados e resolução de problemas estruturais.

#### Nível 1: Básico Geração de Sequências e Tipagem de Dados



O foco desta etapa é criar e padronizar vetores de dados gerados automaticamente.

**Passo 1:** Crie um array representando os 30 dias de um mês de faturamento utilizando a função np.arange(1, 31).


In [23]:
# Criando o array com os 30 dias do mês
# O primeiro parâmetro é inclusivo e o segundo é exclusivo, por isso vai de 1 até 30
dias_mes = np.arange(1, 31)

# Exibindo o resultado
print("Dias do mês de faturamento:")
print(dias_mes)

Dias do mês de faturamento:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


**Passo 2:** Simule 5 metas de vendas igualmente espaçadas entre R$ 20.000 e R$ 30.000 para uma equipe ao longo da semana utilizando a função np.linspace(20000, 30000, 5).



In [24]:
# Gerando 5 metas de vendas igualmente espaçadas
metas_semana = np.linspace(20000, 30000, 5)

# Exibindo o resultado
print("Metas de vendas para a equipe (R$):")
print(metas_semana)

Metas de vendas para a equipe (R$):
[20000. 22500. 25000. 27500. 30000.]


**Passo 3:** O sistema de logística exportou a contagem de estoque físico como números decimais (ex: np.array([10.5, 20.1, 30.9])). Converta este array diretamente para números inteiros utilizando o método .astype(int).



In [25]:
# Array original exportado com números decimais
estoque_decimal = np.array([10.5, 20.1, 30.9])

# Convertendo os dados para o tipo inteiro (descarta a parte decimal)
estoque_inteiro = estoque_decimal.astype(int)

# Exibindo os resultados
print("Estoque em decimais:", estoque_decimal)
print("Estoque corrigido (inteiros):", estoque_inteiro)

Estoque em decimais: [10.5 20.1 30.9]
Estoque corrigido (inteiros): [10 20 30]


**Passo 4:** A partir do array de dias do mês criado no Passo 1, capture os últimos 5 dias e inverta a ordem (do mais recente para o mais antigo) através do fatiamento com passo negativo [::-1].



In [26]:
# Utilizando fatiamento para pegar os últimos 5 elementos e invertendo a ordem com [::-1]
ultimos_5_dias_invertidos = dias_mes[-5:][::-1]

# Outra forma direta de fazer isso em um único fatiamento seria: dias_mes[:-6:-1]

# Exibindo o resultado
print("Últimos 5 dias invertidos:")
print(ultimos_5_dias_invertidos)

Últimos 5 dias invertidos:
[30 29 28 27 26]


#### Nível 2: Intermediário Redimensionamento e Proteção de Dados



Aqui, o objetivo é manipular o formato (shape) das matrizes e entender como o Python gerencia a memória durante o fatiamento.

**Passo 1:** Você recebeu um array unidimensional com o total de visitas de um portal em 12 meses. Utilize o método .reshape(4, 3) para reorganizar automaticamente esses elementos em uma matriz de 4 trimestres (4 linhas e 3 colunas).



In [27]:
# Criando um array unidimensional representando 12 meses de visitas
visitas_anuais = np.arange(1, 13)

# Reorganizando em uma matriz de 4 linhas e 3 colunas
visitas_trimestrais = visitas_anuais.reshape(4, 3)

# Exibindo os resultados
print("Visitas Anuais (1D):")
print(visitas_anuais)
print("\nVisitas Trimestrais (2D - 4x3):")
print(visitas_trimestrais)

Visitas Anuais (1D):
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Visitas Trimestrais (2D - 4x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Passo 2:** A equipe de marketing enviou os dados do primeiro semestre e a equipe comercial enviou os do segundo semestre. Combine essas duas matrizes empilhando-as verticalmente com a função np.vstack().


In [28]:
# Criando matrizes de exemplo para os semestres (2 linhas e 3 colunas cada)
primeiro_semestre = np.array([[10, 12, 15],
                              [18, 20, 22]])

segundo_semestre = np.array([[25, 28, 30],
                             [32, 35, 40]])

# Empilhando as matrizes verticalmente com np.vstack (passamos uma tupla com as matrizes)
dados_consolidados = np.vstack((primeiro_semestre, segundo_semestre))

# Exibindo os resultados
print("Primeiro Semestre:\n", primeiro_semestre)
print("\nSegundo Semestre:\n", segundo_semestre)
print("\nMatriz Consolidada (Empilhada Verticalmente):\n", dados_consolidados)

Primeiro Semestre:
 [[10 12 15]
 [18 20 22]]

Segundo Semestre:
 [[25 28 30]
 [32 35 40]]

Matriz Consolidada (Empilhada Verticalmente):
 [[10 12 15]
 [18 20 22]
 [25 28 30]
 [32 35 40]]


**Passo 3:** Extraia apenas o primeiro trimestre da matriz para criar um cenário de projeção no Google Colab. Para evitar a "pegadinha" onde alterar a nova fatia modifica o array original por acidente, utilize o método.copy() no momento do fatiamento.

Para este passo, vamos utilizar a matriz `visitas_trimestrais` que criamos no Passo 1, onde cada linha representa um trimestre.


In [29]:
# Extraindo o primeiro trimestre (primeira linha, índice 0) e usando .copy()
projecao_q1 = visitas_trimestrais[0].copy()

# Alterando um valor na projeção para demonstrar a proteção
projecao_q1[0] = 999

# Exibindo os resultados para provar que a matriz original não foi afetada
print("Cenário de Projeção Modificado (Q1):")
print(projecao_q1)

print("\nMatriz Original Intacta (Visitas Trimestrais):")
print(visitas_trimestrais)

Cenário de Projeção Modificado (Q1):
[999   2   3]

Matriz Original Intacta (Visitas Trimestrais):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Passo 4:** Para exportar os dados estruturados de volta para um formato de relatório corrido, utilize o método ravel() para achatar a matriz bidimensional de volta em um array 1D.

Para este exemplo, vamos "achatar" a matriz `dados_consolidados` (que criamos no Passo 2) de volta para uma única linha.


In [30]:
# Utilizando o método ravel() para achatar a matriz bidimensional
relatorio_corrido = dados_consolidados.ravel()

# Exibindo os resultados
print("Matriz original 2D (dados consolidados):")
print(dados_consolidados)

print("\nFormato de relatório corrido (Array 1D achatado com ravel):")
print(relatorio_corrido)

Matriz original 2D (dados consolidados):
[[10 12 15]
 [18 20 22]
 [25 28 30]
 [32 35 40]]

Formato de relatório corrido (Array 1D achatado com ravel):
[10 12 15 18 20 22 25 28 30 32 35 40]


#### Nível 3: Avançado - Ranking, Broadcasting e Resolução de Sistemas



Esta etapa explora álgebra linear e manipulação de dimensões para análise de cenários.

**Passo 1:** Você possui as seguintes pontuações de alunos em uma avaliação de pensamento computacional: np.array([85, 92, 78, 95, 88]). Em vez de apenas ordenar os valores, utilize np.argsort() para obter os índices dessa ordenação, permitindo descobrir rapidamente a posição de cada aluno no ranking geral.



In [32]:
# Array com as pontuações dos alunos
pontuacoes = np.array([85, 92, 78, 95, 88])

# Obtendo os índices que ordenariam o array (crescente por padrão)
indices_ordenacao = np.argsort(pontuacoes)

# Exibindo os resultados
print("Pontuações originais:", pontuacoes)
print("Índices da ordenação:", indices_ordenacao)

# Bônus: mostrando as pontuações na ordem utilizando os índices
print("Pontuações ordenadas (do menor para o maior):", pontuacoes[indices_ordenacao])

Pontuações originais: [85 92 78 95 88]
Índices da ordenação: [2 0 4 1 3]
Pontuações ordenadas (do menor para o maior): [78 85 88 92 95]


**Passo 2:** Você possui um vetor contendo preços base em formato de linha. Insira uma nova dimensão neste vetor utilizando np.newaxis para transformá-lo estruturalmente em uma coluna. Isso prepara a matriz para cruzar e aplicar múltiplos percentuais de desconto simultaneamente via regras de broadcasting.

In [33]:
# Vetor contendo preços base em formato de linha (1D)
precos_base = np.array([100, 150, 200, 250])

# Inserindo uma nova dimensão para transformar o vetor em coluna (2D)
precos_coluna = precos_base[:, np.newaxis]

# Exibindo os resultados e seus respectivos formatos (shapes)
print(f"Preços em linha - Formato {precos_base.shape}:")
print(precos_base)

print(f"\nPreços em coluna - Formato {precos_coluna.shape}:")
print(precos_coluna)

Preços em linha - Formato (4,):
[100 150 200 250]

Preços em coluna - Formato (4, 1):
[[100]
 [150]
 [200]
 [250]]


**Passo 3:** Descubra o custo unitário exato de dois recursos de hardware para um laboratório. O projeto A usou 2 placas robóticas e 1 sensor, custando 500 reais no total. O projeto B usou 1 placa robótica e devolveu 1 sensor (estorno), custando 100 reais no total. Crie a matriz de coeficientes A e o vetor de resultados b, aplicando a função np.linalg.solve(A, b) para encontrar os valores individuais das peças sem realizar o cálculo manual.

Para resolver esse sistema de equações lineares, montamos a matriz com a quantidade de peças e o vetor com os totais em reais:



In [34]:
# Criando a matriz A com os coeficientes (quantidade de placas e sensores)
# Projeto A: 2 placas, 1 sensor
# Projeto B: 1 placa, -1 sensor (devolvido)
matriz_a = np.array([[2, 1],
                     [1, -1]])

# Criando o vetor b com os resultados (custo total de cada projeto)
vetor_b = np.array([500, 100])

# Resolvendo o sistema linear
valores_individuais = np.linalg.solve(matriz_a, vetor_b)

# Extraindo os resultados
valor_placa = valores_individuais[0]
valor_sensor = valores_individuais[1]

# Exibindo os resultados
print(f"Custo unitário da Placa Robótica: R$ {valor_placa:.2f}")
print(f"Custo unitário do Sensor: R$ {valor_sensor:.2f}")

Custo unitário da Placa Robótica: R$ 200.00
Custo unitário do Sensor: R$ 100.00
